# Generated by Django 4.0.4 on 2022-05-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms', models.BooleanField(default=False, verbose_name='I agree to the terms and conditions')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sub', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
